swagger: '2.0'
info:
  title: Device unenrollment
  description: API to unenroll a device.
  contact:
    name: 'VMware, Inc.'
  license:
    name: 'Copyright © 2021 VMware, Inc. All rights reserved.'
  version: '1'
host: www.api.vmware.com
basePath: /devices
security:
  - bearerAuth: []
x-internalApi: override
paths:
  '/{device-uuid}/unenroll':
    post:
      tags:
        - DeviceUnenrollment
      summary: Unenroll the given device from the system.
      operationId: UnEnrollDevice
      parameters:
        - name: device-uuid
          in: path
          description: UUID of the device.
          required: true
          format: uuid
          type: string
      responses:
        '200':
          description: Ok
        '401':
            description: |
              Unauthorized.
                1. { 1003: Invalid token or issuer. }
                2. { 1004: No credentials provided. }
        '403':
            description: |
              Forbidden
                1. { 5143: User does not have access to the device. }
        '404':
            description: |
              NotFound
                1. { 5061: Device not found for specified UUID. }

x-attributes:
  - TokenServiceAuthorization("uem-api")
  - IgnoreXmlMediaType
